-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.CSVFile (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  name text NOT NULL,
  url text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status text NOT NULL DEFAULT 'pending'::text,
  totalRows integer NOT NULL DEFAULT 0,
  validRows integer NOT NULL DEFAULT 0,
  invalidRows integer NOT NULL DEFAULT 0,
  CONSTRAINT CSVFile_pkey PRIMARY KEY (id)
);
CREATE TABLE public.CSVRow (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  fileId text NOT NULL,
  rowData jsonb NOT NULL,
  rowIndex integer NOT NULL,w
  isValid boolean NOT NULL DEFAULT true,
  errors text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CSVRow_pkey PRIMARY KEY (id),
  CONSTRAINT CSVRow_fileId_fkey FOREIGN KEY (fileId) REFERENCES public.CSVFile(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_user_id text NOT NULL UNIQUE,
  name text NOT NULL,
  website text,
  industry text,
  size USER-DEFINED,
  social_links jsonb DEFAULT '{}'::jsonb,
  keywords ARRAY DEFAULT '{}'::text[],
  competitors ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_brand_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_profile_id uuid,
  brand_analysis jsonb NOT NULL,
  analysis_version integer DEFAULT 1,
  changes_detected jsonb DEFAULT '{}'::jsonb,
  confidence_score numeric,
  source_data_hash text,
  analyzed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_brand_history_pkey PRIMARY KEY (id),
  CONSTRAINT company_brand_history_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id)
);
CREATE TABLE public.company_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_profile_id uuid,
  user_id uuid,
  title text NOT NULL,
  description text,
  document_type text NOT NULL,
  file_name text NOT NULL,
  file_size integer,
  mime_type text,
  storage_path text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'company-documents'::text,
  processing_status text DEFAULT 'pending'::text,
  extracted_text text,
  summary text,
  tags ARRAY,
  ai_analysis jsonb DEFAULT '{}'::jsonb,
  sentiment_score numeric,
  key_topics ARRAY,
  visibility text DEFAULT 'private'::text,
  access_permissions jsonb DEFAULT '{}'::jsonb,
  uploaded_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_documents_pkey PRIMARY KEY (id),
  CONSTRAINT company_documents_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id),
  CONSTRAINT company_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.company_enrichments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid UNIQUE,
  description text,
  category text,
  summary_sections jsonb,
  funding_status text,
  total_funding numeric,
  last_funding_date date,
  funding_rounds jsonb,
  linkedin_url text,
  linkedin_employee_count integer,
  linkedin_followers integer,
  founders jsonb DEFAULT '[]'::jsonb,
  enriched_competitors jsonb DEFAULT '[]'::jsonb,
  company_intelligence text,
  market_position text,
  growth_indicators jsonb,
  seo_analysis_completed boolean DEFAULT false,
  seo_analysis_timestamp timestamp with time zone,
  seo_analysis_data jsonb,
  enrichment_source text,
  enrichment_timestamp timestamp with time zone DEFAULT now(),
  raw_enrichment_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_enrichments_pkey PRIMARY KEY (id),
  CONSTRAINT company_enrichments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.company_insights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_profile_id uuid,
  insight_type text NOT NULL,
  title text NOT NULL,
  description text,
  confidence_score numeric,
  insight_data jsonb NOT NULL,
  source_references jsonb DEFAULT '[]'::jsonb,
  category text,
  priority text DEFAULT 'medium'::text,
  tags ARRAY,
  validated_by uuid,
  validated_at timestamp with time zone,
  validation_notes text,
  generated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_insights_pkey PRIMARY KEY (id),
  CONSTRAINT company_insights_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id),
  CONSTRAINT company_insights_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.company_marketing_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_profile_id uuid,
  user_id uuid,
  campaign_name text,
  description text,
  status text DEFAULT 'generating'::text,
  brand_analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  email_templates jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_templates integer DEFAULT 0,
  generated_at timestamp with time zone DEFAULT now(),
  processing_time integer,
  error_message text,
  templates_used integer DEFAULT 0,
  total_sends integer DEFAULT 0,
  total_opens integer DEFAULT 0,
  total_clicks integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_marketing_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT company_marketing_campaigns_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id),
  CONSTRAINT company_marketing_campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.company_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  website_url text NOT NULL UNIQUE,
  last_enriched_at timestamp with time zone,
  enrichment_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  social_links jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_social_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  social_profile_id uuid,
  platform_post_id text NOT NULL,
  post_type text NOT NULL,
  content_text text,
  media_urls ARRAY,
  post_url text,
  likes_count integer DEFAULT 0,
  shares_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  views_count integer DEFAULT 0,
  sentiment_score numeric,
  engagement_rate numeric,
  topics ARRAY,
  mentions ARRAY,
  hashtags ARRAY,
  posted_at timestamp with time zone NOT NULL,
  scraped_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_social_content_pkey PRIMARY KEY (id),
  CONSTRAINT company_social_content_social_profile_id_fkey FOREIGN KEY (social_profile_id) REFERENCES public.company_social_profiles(id)
);
CREATE TABLE public.company_social_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_profile_id uuid,
  platform text NOT NULL,
  profile_url text NOT NULL,
  username text,
  handle text,
  verified boolean DEFAULT false,
  follower_count integer,
  following_count integer,
  post_count integer,
  bio text,
  profile_image_url text,
  last_scraped_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  scraped_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_social_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT company_social_profiles_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id)
);
CREATE TABLE public.doc_processor_document_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid,
  chunk_index integer NOT NULL,
  content text NOT NULL,
  token_count integer NOT NULL,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  page_number integer,
  heading text,
  CONSTRAINT doc_processor_document_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT doc_processor_document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.doc_processor_documents(id)
);
CREATE TABLE public.doc_processor_document_entities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid,
  entity_type text NOT NULL,
  entity_text text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doc_processor_document_entities_pkey PRIMARY KEY (id),
  CONSTRAINT doc_processor_document_entities_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.doc_processor_documents(id)
);
CREATE TABLE public.doc_processor_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  file_path text NOT NULL,
  file_type USER-DEFINED NOT NULL,
  file_size bigint NOT NULL,
  mime_type text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::document_status,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  user_id uuid,
  page_count integer,
  word_count integer,
  language text,
  summary text,
  keywords ARRAY,
  analysis jsonb,
  file_hash text UNIQUE,
  extracted_text text,
  metadata jsonb,
  CONSTRAINT doc_processor_documents_pkey PRIMARY KEY (id),
  CONSTRAINT doc_processor_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.doc_processor_processing_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid,
  task_type text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::document_status,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT doc_processor_processing_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT doc_processor_processing_tasks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.doc_processor_documents(id)
);
CREATE TABLE public.email_campaign_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  period_type text NOT NULL,
  emails_sent integer DEFAULT 0,
  emails_delivered integer DEFAULT 0,
  emails_opened integer DEFAULT 0,
  emails_clicked integer DEFAULT 0,
  emails_bounced integer DEFAULT 0,
  emails_complained integer DEFAULT 0,
  emails_unsubscribed integer DEFAULT 0,
  delivery_rate numeric,
  open_rate numeric,
  click_rate numeric,
  click_to_open_rate numeric,
  bounce_rate numeric,
  complaint_rate numeric,
  unsubscribe_rate numeric,
  total_revenue numeric,
  revenue_per_email numeric,
  template_performance jsonb DEFAULT '{}'::jsonb,
  calculated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_campaign_performance_pkey PRIMARY KEY (id),
  CONSTRAINT email_campaign_performance_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.company_marketing_campaigns(id)
);
CREATE TABLE public.email_template_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  user_id uuid,
  template_id text NOT NULL,
  template_name text NOT NULL,
  template_purpose text NOT NULL,
  template_theme text NOT NULL,
  recipient_email text,
  recipient_name text,
  recipient_company text,
  personalization_data jsonb DEFAULT '{}'::jsonb,
  email_service_provider text,
  email_service_id text,
  sent_at timestamp with time zone,
  opened_at timestamp with time zone,
  first_click_at timestamp with time zone,
  total_clicks integer DEFAULT 0,
  bounced boolean DEFAULT false,
  complained boolean DEFAULT false,
  unsubscribed boolean DEFAULT false,
  ab_test_variant text,
  ab_test_group text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_template_usage_pkey PRIMARY KEY (id),
  CONSTRAINT email_template_usage_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.company_marketing_campaigns(id),
  CONSTRAINT email_template_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.enrichment_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  website_url text NOT NULL,
  enrichment_types ARRAY NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  total_duration integer,
  total_requested integer NOT NULL DEFAULT 0,
  successful integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0,
  skipped integer NOT NULL DEFAULT 0,
  CONSTRAINT enrichment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT enrichment_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.enrichment_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid,
  type text NOT NULL,
  status text NOT NULL,
  data jsonb,
  error_message text,
  duration integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT enrichment_results_pkey PRIMARY KEY (id),
  CONSTRAINT enrichment_results_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.enrichment_requests(id)
);
CREATE TABLE public.marketing_automation_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_profile_id uuid,
  user_id uuid,
  name text NOT NULL,
  description text,
  status text DEFAULT 'draft'::text,
  trigger_type text NOT NULL,
  trigger_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  workflow_steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  current_step integer DEFAULT 0,
  email_templates jsonb DEFAULT '[]'::jsonb,
  total_enrollments integer DEFAULT 0,
  active_enrollments integer DEFAULT 0,
  completed_enrollments integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_triggered_at timestamp with time zone,
  CONSTRAINT marketing_automation_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_automation_workflows_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id),
  CONSTRAINT marketing_automation_workflows_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.onboarding_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid UNIQUE,
  clerk_user_id text NOT NULL,
  onboarding_completed boolean DEFAULT false,
  onboarding_completed_at timestamp with time zone,
  current_step text,
  completed_steps ARRAY DEFAULT '{}'::text[],
  form_data_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT onboarding_progress_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_progress_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.user_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid UNIQUE,
  clerk_user_id text NOT NULL,
  goals ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_goals_pkey PRIMARY KEY (id),
  CONSTRAINT user_goals_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.users (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  clerk_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  name text,
  role text DEFAULT 'member'::text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workflow_id uuid,
  contact_email text NOT NULL,
  contact_name text,
  contact_company text,
  contact_metadata jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'active'::text,
  current_step integer DEFAULT 0,
  steps_completed integer DEFAULT 0,
  emails_sent integer DEFAULT 0,
  emails_opened integer DEFAULT 0,
  emails_clicked integer DEFAULT 0,
  enrolled_at timestamp with time zone DEFAULT now(),
  last_activity_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_enrollments_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.marketing_automation_workflows(id)
);
CREATE TABLE public.wrappers_fdw_stats (
  fdw_name text NOT NULL,
  create_times bigint,
  rows_in bigint,
  rows_out bigint,
  bytes_in bigint,
  bytes_out bigint,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT wrappers_fdw_stats_pkey PRIMARY KEY (fdw_name)
);