"use client";

import { FC } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Target, Shield, ArrowRight, Zap, TrendingUp, Eye } from "lucide-react";
import { cn } from "@/utils/utils";
import { useScrollAnimation } from "@/hooks/use-scroll-animation";
import { HijackingSystemWorkflow } from "./hijacking-system-workflow";
import { BackgroundDots } from "../../components/background";

const systemBenefits = [
  {
    icon: Eye,
    title: "Identify Competitor Website Visitors",
    description:
      "Track visitors in real-time across your competitors' websites using our 1.9 trillion signal database.",
    highlight: "Real-time tracking",
  },
  {
    icon: Shield,
    title: "100% Legal Data Collection",
    description:
      "All data sourced from public information and fully compliant with GDPR, CCPA, and privacy regulations.",
    highlight: "Fully compliant",
  },
  {
    icon: Zap,
    title: "Automated Email Campaigns",
    description:
      "Personalized campaigns launch automatically when prospects visit competitor sites.",
    highlight: "5-minute delivery",
  },
  {
    icon: TrendingUp,
    title: "Turn Competitor Ad Spend Into Your Advantage",
    description:
      "Capture the leads generated by your competitors' marketing investments.",
    highlight: "80% cost savings",
  },
];

export const HijackingSystemFeatureSection: FC = () => {
  const { elementRef, isInView } = useScrollAnimation({ threshold: 0.1 });

  return (
    <section
      ref={elementRef as any}
      className={cn(
        "bg-muted w-full bg-gradient-to-br py-12 transition-all duration-1000 md:py-24 lg:py-32",
        isInView ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0",
      )}
    >
      <BackgroundDots />
      <div className="container mx-auto px-4 md:px-6">
        {/* Section Header */}
        <div className="mb-16 text-center">
          <div
            className={cn(
              "bg-primary/10 border-primary/20 text-primary mb-6 inline-flex items-center rounded-full border px-4 py-2 text-sm font-medium transition-all delay-200 duration-700",
              isInView ? "scale-100 opacity-100" : "scale-95 opacity-0",
            )}
          >
            <Target className="mr-2 h-4 w-4" />
            Featured System
          </div>

          <h2
            className={cn(
              "mb-4 text-3xl font-bold tracking-tighter transition-all delay-300 duration-700 sm:text-4xl md:text-5xl",
              isInView
                ? "translate-y-0 opacity-100"
                : "translate-y-4 opacity-0",
            )}
          >
            The Hijacking System
          </h2>

          <p
            className={cn(
              "text-muted-foreground mx-auto mb-4 max-w-3xl text-xl transition-all delay-400 duration-700",
              isInView
                ? "translate-y-0 opacity-100"
                : "translate-y-4 opacity-0",
            )}
          >
            How We Turn Your Competitors Into Lead Generators
          </p>

          <p
            className={cn(
              "text-muted-foreground mx-auto max-w-4xl text-lg transition-all delay-500 duration-700",
              isInView
                ? "translate-y-0 opacity-100"
                : "translate-y-4 opacity-0",
            )}
          >
            Our proprietary system identifies and captures visitors from your
            competitors' websites, turning their marketing spend into your lead
            pipeline.
          </p>
        </div>

        {/* Benefits Section */}
        <div
          className={cn(
            "mb-16 grid grid-cols-1 gap-6 transition-all delay-600 duration-1000 md:grid-cols-2",
            isInView ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0",
          )}
        >
          {systemBenefits.map((benefit, index) => (
            <Card
              key={index}
              className="border-border/50 hover:border-primary/30 transition-all duration-300 hover:scale-[1.02] hover:shadow-lg"
            >
              <CardContent className="p-6">
                <div className="flex items-start space-x-4">
                  <div className="flex-shrink-0">
                    <div className="bg-primary/10 flex h-12 w-12 items-center justify-center rounded-lg">
                      {/* <benefit.icon className="text-primary h-6 w-6" /> */}
                    </div>
                  </div>
                  <div className="flex-1">
                    <h3 className="mb-2 text-lg font-semibold">
                      {benefit.title}
                    </h3>
                    <p className="text-muted-foreground mb-2">
                      {benefit.description}
                    </p>
                    <div className="bg-primary/10 text-primary inline-flex items-center rounded-full px-3 py-1 text-xs font-medium">
                      {benefit.highlight}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Process Workflow */}
        {/* <div className={cn(
          "mb-16 transition-all duration-1000 delay-800",
          isInView ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
        )}>
        </div> */}
        {/* <HijackingSystemWorkflow /> */}

        {/* Stats Bar */}
        <div
          className={cn(
            "bg-background border-border/50 mb-12 rounded-lg border p-6 transition-all delay-1000 duration-1000",
            isInView ? "translate-y-0 opacity-100" : "translate-y-4 opacity-0",
          )}
        >
          <div className="grid grid-cols-2 gap-6 text-center md:grid-cols-4">
            <div>
              <div className="text-primary text-2xl font-bold">1.9T+</div>
              <div className="text-muted-foreground text-sm">
                Intent Signals
              </div>
            </div>
            <div>
              <div className="text-primary text-2xl font-bold">270M</div>
              <div className="text-muted-foreground text-sm">US Consumers</div>
            </div>
            <div>
              <div className="text-primary text-2xl font-bold">60-70%</div>
              <div className="text-muted-foreground text-sm">
                Identity Match
              </div>
            </div>
            <div>
              <div className="text-primary text-2xl font-bold">5 Min</div>
              <div className="text-muted-foreground text-sm">Speed to Lead</div>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div
          className={cn(
            "text-center transition-all delay-1100 duration-1000",
            isInView ? "translate-y-0 opacity-100" : "translate-y-4 opacity-0",
          )}
        >
          <div className="bg-primary/5 border-primary/20 rounded-lg border p-8">
            <h3 className="mb-4 text-2xl font-bold">
              Ready to See The Hijacking System in Action?
            </h3>
            <p className="text-muted-foreground mx-auto mb-6 max-w-2xl">
              Watch how we turn your competitors' website traffic into your
              qualified leads, all while maintaining 100% legal compliance.
            </p>

            <div className="flex flex-col justify-center gap-4 sm:flex-row">
              <Button size="lg" className="px-8 py-3">
                See The System In Action
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button variant="outline" size="lg" className="px-8 py-3">
                Get Free Analysis
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HijackingSystemFeatureSection;
