"use client";

// External imports
import Link from "next/link";
import {
  ArrowRight,
  LineChart,
  TrendingUp,
  Users,
  Target,
  Shield,
  Zap,
  Eye,
  Activity,
  Map as MapIcon,
  MessageCircle,
} from "lucide-react";
import { Area, AreaChart, CartesianGrid } from "recharts";

// Internal imports
import { Button } from "@/components/ui/button";
import { cn } from "@/utils/utils";
import { Logo } from "@/components/logo";
import {
  type ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart";
// import { IntentSequenceMultipleInputs } from "../../components/intent-sequence-animated-beam/IntentSequenceMultipleInputs";
// import { DotPattern } from "@/components/dot-pattern";
// import { TrustedBySection } from "@/components/shared/TrustedBySection";

import { TrustedBySection } from "@/components/shared/TrustedBySection";

import React from "react";
import { AnimatePresence, motion, useAnimationFrame } from "motion/react";
import { useRef, useState } from "react";
import RadialOrbitalTimeline from "@/components/ui/radial-orbital-timeline";
import { useScrollAnimation } from "@/hooks/use-scroll-animation";
import { Card, CardContent } from "@/components/ui/card";
import { BackgroundDots } from "@/components/background";
import { WorldMap } from "@/components/ui/world-map";



/**
 * CTAButton component for consistent call-to-action buttons
 */
export const CTAButton = ({
  children,
  variant = "default",
  href,
  icon,
}: {
  children: React.ReactNode;
  variant?: "default" | "outline";
  href?: string;
  icon?: React.ReactNode;
}) => {
  const buttonClass = cn(
    "h-16 px-8 text-base font-semibold tracking-wide uppercase sm:text-lg",
    variant === "outline" && "hover:bg-background/5 border-2",
  );

  const button = (
    <Button size="lg" variant={variant} className={buttonClass}>
      {icon && (
        <span
          className="bg-primary-foreground/10 -ml-2 inline-flex h-8 w-8 items-center justify-center rounded-full"
          aria-hidden="true"
        >
          {icon}
        </span>
      )}
      {children}
    </Button>
  );

  if (href) {
    return <Link href={href}>{button}</Link>;
  }

  return button;
};

const systemBenefits = [
  {
    icon: Eye,
    title: "Identify Competitor Website Visitors",
    description:
      "Track visitors in real-time across your competitors' websites using our 1.9 trillion signal database.",
    highlight: "Real-time tracking",
  },
  {
    icon: Shield,
    title: "100% Legal Data Collection",
    description:
      "All data sourced from public information and fully compliant with GDPR, CCPA, and privacy regulations.",
    highlight: "Fully compliant",
  },
  {
    icon: Zap,
    title: "Automated Email Campaigns",
    description:
      "Personalized campaigns launch automatically when prospects visit competitor sites.",
    highlight: "5-minute delivery",
  },
  {
    icon: TrendingUp,
    title: "Turn Competitor Ad Spend Into Your Advantage",
    description:
      "Capture the leads generated by your competitors' marketing investments.",
    highlight: "80% cost savings",
  },
];

/**
 * FeaturesSection component for the hijacking system replacement
 */
const FeaturesSection = () => {
  const chartConfig = {
    competitors: {
      label: "Competitor Traffic",
      color: "#ef4444",
    },
    captured: {
      label: "Captured Leads",
      color: "#22c55e",
    },
  } satisfies ChartConfig;

  const chartData = [
    { month: "Jan", competitors: 156, captured: 124 },
    { month: "Feb", competitors: 224, captured: 189 },
    { month: "Mar", competitors: 326, captured: 287 },
    { month: "Apr", competitors: 405, captured: 367 },
    { month: "May", competitors: 489, captured: 445 },
    { month: "Jun", competitors: 567, captured: 523 },
  ];

  // Competitor tracking dots for the world map
  const competitorDots = [
    {
      start: { lat: 40.7128, lng: -74.006 }, // New York
      end: { lat: 37.7749, lng: -122.4194 }, // San Francisco
    },
    {
      start: { lat: 51.5074, lng: -0.1278 }, // London
      end: { lat: 40.7128, lng: -74.006 }, // New York
    },
    {
      start: { lat: 35.6762, lng: 139.6503 }, // Tokyo
      end: { lat: 37.7749, lng: -122.4194 }, // San Francisco
    },
  ];

  const MonitoringChart = () => {
    return (
      <ChartContainer
        className="aspect-auto h-[30rem] md:h-96"
        config={chartConfig}
      >
        <AreaChart
          accessibilityLayer
          data={chartData}
          margin={{
            left: 0,
            right: 0,
          }}
        >
          <defs>
            <linearGradient id="fillCompetitors" x1="0" y1="0" x2="0" y2="1">
              <stop
                offset="0%"
                stopColor="var(--color-competitors)"
                stopOpacity={0.8}
              />
              <stop
                offset="55%"
                stopColor="var(--color-competitors)"
                stopOpacity={0.1}
              />
            </linearGradient>
            <linearGradient id="fillCaptured" x1="0" y1="0" x2="0" y2="1">
              <stop
                offset="0%"
                stopColor="var(--color-captured)"
                stopOpacity={0.8}
              />
              <stop
                offset="55%"
                stopColor="var(--color-captured)"
                stopOpacity={0.1}
              />
            </linearGradient>
          </defs>
          <CartesianGrid vertical={false} />
          <ChartTooltip
            active
            cursor={false}
            content={<ChartTooltipContent className="dark:bg-muted" />}
          />
          <Area
            strokeWidth={2}
            dataKey="competitors"
            type="stepBefore"
            fill="url(#fillCompetitors)"
            fillOpacity={0.1}
            stroke="var(--color-competitors)"
            stackId="a"
          />
          <Area
            strokeWidth={2}
            dataKey="captured"
            type="stepBefore"
            fill="url(#fillCaptured)"
            fillOpacity={0.1}
            stroke="var(--color-captured)"
            stackId="a"
          />
        </AreaChart>
      </ChartContainer>
    );
  };

  return (
    <section className="px-4 py-16 md:py-32">
      <div className="mx-auto grid max-w-5xl border md:grid-cols-2">
        <div className="relative h-full w-full overflow-hidden">
          <div className="relative z-20 p-6 sm:p-12">
            <span className="text-white flex items-center gap-2">
              <Eye className="size-4" />
              Real-time Visitor Identification
            </span>

            <p className="mt-8 text-2xl font-semibold">
              Track visitors across your competitors' websites using our 1.9
              trillion signal database.
            </p>

            {/* Bot Protection Visualization */}
            <div className="text-white mt-8 text-sm">
              Real-time bot protection and visitor analysis
            </div>
          </div>

          {/* World Map Background */}
          <div className="absolute inset-0 flex items-center justify-center opacity-30">
            <WorldMap
              dots={competitorDots}
              lineColor="#ef4444"
              transparentBackground
            />
          </div>

          {/* Notification Badge */}
          <div className="absolute right-6 bottom-6 left-6 z-20">
            <div className="bg-background dark:bg-muted flex items-center gap-2 rounded-md border px-3 py-2 text-xs font-medium shadow-md">
              <span className="text-lg">🎯</span> Visitor from competitor site
              detected
            </div>
          </div>
        </div>

        <div className="overflow-hidden border-t bg-transparent p-6 sm:p-12 md:border-0 md:border-l">
          <div className="relative z-10">
            <span className="text-white flex items-center gap-2">
              <Zap className="size-4" />
              Automated Email Campaigns
            </span>

            <p className="my-8 text-2xl font-semibold">
              Personalized campaigns launch automatically when prospects visit
              competitor sites.
            </p>
          </div>
          <div aria-hidden className="flex flex-col gap-8">
            <div>
              <div className="flex items-center gap-2">
                <span className="flex size-5 rounded-full border">
                  <Logo className="m-auto size-3" />
                </span>
                <span className="text-white text-xs">
                  5 minutes ago
                </span>
              </div>
              <div className="bg-background mt-1.5 w-3/5 rounded-md border p-3 text-xs">
                Prospect visited competitor's pricing page
              </div>
            </div>

            <div>
              <div className="mb-1 ml-auto w-3/5 rounded-md bg-blue-600 p-3 text-xs text-white">
                Hi! I noticed you're exploring solutions. We offer 40% better
                ROI than [competitor]. Can I show you how?
              </div>
              <span className="text-white block text-right text-xs">
                Sent automatically
              </span>
            </div>
          </div>
        </div>
        <div className="col-span-full border-y p-12">
          <p className="text-center text-4xl font-semibold lg:text-7xl">
            60-70% Identity Match Rate
          </p>
        </div>
        <div className="relative col-span-full">
          <div className="absolute z-10 max-w-lg px-6 pt-6 pr-12 md:px-12 md:pt-12">
            <span className="text-white flex items-center gap-2">
              <TrendingUp className="size-4" />
              Competitor Traffic Conversion
            </span>

            <p className="my-8 text-2xl font-semibold">
              Turn your competitors' marketing spend into your lead pipeline.{" "}
              <span className="text-white">
                {" "}
                Track and convert their website visitors in real-time.
              </span>
            </p>
          </div>
          <MonitoringChart />
        </div>
      </div>
    </section>
  );
};

export function HijackHero() {
  // Animation for feature section
  const { elementRef, isInView } = useScrollAnimation({ threshold: 0.1 });

  return (
    <section
      className="relative overflow-hidden"
      // id="home"
      aria-labelledby="hero-heading"
    >
      {/* Background elements */}
      <div
        className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:12px_12px]"
        aria-hidden="true"
      />
      <div
        className="absolute top-[30%] right-[40%] z-[-10px] h-[400px] w-[400px] rounded-full bg-[turquoise]/10 blur-2xl"
        aria-hidden="true"
      />
      <div
        className="bg-primary/20 absolute bottom-16 left-0 -z-10 h-36 w-36 rounded-full blur-3xl"
        aria-hidden="true"
      />

      <div className="relative mx-auto flex max-w-7xl flex-col items-center px-4 py-32 sm:px-6 sm:py-40 lg:px-8">
        
        <section
          ref={elementRef as any}
          className={cn(
            "bg-muted w-full bg-gradient-to-br py-12 transition-all duration-1000",
            isInView ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0",
          )}
        >
          <div className="container mx-auto px-4 md:px-6">
            {/* Section Header */}
            <div className="mb-16 text-center">
              <div
                className={cn(
                  "bg-primary/10 border-primary/20 text-primary mb-6 inline-flex items-center rounded-full border px-4 py-2 text-sm font-medium transition-all delay-200 duration-700",
                  isInView ? "scale-100 opacity-100" : "scale-95 opacity-0",
                )}
              >
                <Target className="mr-2 h-4 w-4" />
                Featured System
              </div>

              <h2
                className={cn(
                  "mb-4 text-3xl font-bold tracking-tighter transition-all delay-300 duration-700 sm:text-4xl md:text-5xl",
                  isInView
                    ? "translate-y-0 opacity-100"
                    : "translate-y-4 opacity-0",
                )}
              >
                The Hijacking System
              </h2>

              <h2
                className={cn(
                  "text-white mx-auto mb-4 max-w-3xl text-xl transition-all delay-400 duration-700",
                  isInView
                    ? "translate-y-0 opacity-100"
                    : "translate-y-4 opacity-0",
                )}
              >
                How We Turn Your Competitors Into Lead Generators
              </p>

              <p
                className={cn(
                  "text-white mx-auto max-w-4xl text-lg transition-all delay-500 duration-700",
                  isInView
                    ? "translate-y-0 opacity-100"
                    : "translate-y-4 opacity-0",
                )}
              >
                Our proprietary system identifies and captures visitors from
                your competitors' websites, turning their marketing spend into
                your lead pipeline.
              </p>
            </div>

            {/* Replace the Benefits Section and CTA Section with FeaturesSection */}
            <FeaturesSection />
          </div>
        </section>
        
      </div>
    </section>
  );
}
